apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: localhelp
spec:
  type: NodePort
  selector:
    app: backend
    purpose: deployment
    tier: backend-app
    project: localhelp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
